#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap           6

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# autostart
sxhkd &
picom --config $HOME/.config/picom/picom.conf &
polybar &
dunst &
nitrogen --restore &
#feh --bg-scale ~/WALLPAPERS/wallpaper.jpeg
